### ISSUE TITLE
YMDK YMD09 Firmware

### ISSUE THREAD

**Issue by 8ananaJoe** [the-via/reader#8]
Hi,

i flashed your YMDK YMD09 Firmware on to my YMD09 and now my macropad is not responding anymore at all. Meaning no sign of connection when connecting it to the PC (LEDs not glowing, macropad cant be found in device manager). It's basically just a brick of plastic now.
Any suggestion on how to fix this would be appreciated!

THX!

**Comment by Adolf-Sniffler** [comment]
I have the same issue! I've tried contacting YMDK, but due to the language barrier, I didn't get anywhere...
